version: 2
updates:
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "08:00"
      timezone: Europe/Berlin
    open-pull-requests-limit: 20
    labels:
      - "dependencies 🤗"
    allow:
      - dependency-type: direct
      - dependency-type: indirect
    rebase-strategy: disabled

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "08:00"
      timezone: Europe/Berlin
    open-pull-requests-limit: 20
    labels:
      - GitHub Actions
    rebase-strategy: disabled
